### ISSUE TITLE
评价中京东出现安全验证，无法验证，运行直接报错退出

### ISSUE THREAD

**Issue by xbeyond3** [Goodnameisfordoggy/JD-AutomatedTools#2]
希望大佬增加一个暂停，可以安全验证后，继续评价，谢谢

**Comment by Goodnameisfordoggy** [comment]
> 希望大佬增加一个暂停，可以安全验证后，继续评价，谢谢

# 出于JD的ip风控与个人账号的安全性考虑：
- 建议出现人机验证后停止使用脚本一段时间；出现身份验证，在脚本报错退出后请使用浏览器正常登录并验证；
- 首次使用脚本、在新设备、新ip登录JD账号运行后概率触发风控，一般为几个小时；建议个人账号使用常用设备与ip运行脚本；经过多个账号测试，在常用设备与ip下，即使是首次运行也没有出现风控。（该说法并不绝对）
- 关于暂停功能，在创作时考虑过此功能；但是在触发验证（可视为已经触发风控）后暂停进行手动验证，大概率会触发连环验证或多次人机验证，最终还是被风控；该功能将在以后的版本继续验证其可行性。

**Comment by Goodnameisfordoggy** [comment]
# 关于安全验证与目前最好的办法：
- 根据经验，若触发验证很大概率被风控（大多为几小时，这是正常的网站都会有的安全策略）
- 等待几个小时，或者第二天再次运行，每次运行控制在10个商品以内；若不幸再次出发风控，重复该步骤；在多个账号测试中最“幸运”的账号（该账号新设备，新ip异地登录后运行）在连续3天触发了风控（风控在10个商品评价前均未出现），之后就恢复正常了。
- 不要尝试切换账号运行，一般情况下就是最简单的风控ip策略；切换账号频繁触发人机验证反而可能会被记录账号异常（猜测）

**Comment by xbeyond3** [comment]
好的，谢谢大佬认真的答复，先登录一段时间，等封控过了再评价试试
