### ISSUE TITLE
大佬 能出个详细使用教程吗

### ISSUE THREAD

**Issue by QQ583818598** [Goodnameisfordoggy/JD-AutomatedTools#3]
纯小白  不会使用

**Comment by Goodnameisfordoggy** [comment]
# 对于纯小白如何使用：
- 在仓库主页点击`releases`或直接访问 https://github.com/Goodnameisfordoggy/JD-AutomatedTools/releases ，找到对应脚本最新的发行版下载zip文件，里面提供了打包好的exe文件，运行该exe文件会使用默认参数运行对应脚本。
- 目前仅自动评价脚本发布了发行版，其他脚本敬请期待！

**Comment by QQ583818598** [comment]
感谢大佬解答
